name: Playwright Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright Browsers
        run: pwsh bin/Release/net10.0/playwright.ps1 install

      - name: Run NUnit Tests
        run: dotnet test --configuration Release --logger trx

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: TestResults
          path: "**/*.trx"